-- =========================================================================
-- VIDA NUEVA APP - SCHEMA SQL v1.0
-- Iglesia Bautista Vida Nueva, Santiago, Chile
-- =========================================================================

-- Habilitar la extensión UUID si no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. CREACIÓN DE TABLAS BASE
-- =========================================================================

-- Tabla de Células (grupos pequeños)
CREATE TABLE IF NOT EXISTS public.celulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    lider_id UUID, -- Se vincula a profiles más adelante por FK circular
    dia TEXT,
    hora TEXT,
    lugar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Ministerios
CREATE TABLE IF NOT EXISTS public.ministerios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    coordinador_id UUID, -- Se vincula a profiles más adelante por FK circular
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Perfiles (Extiende a auth.users de Supabase)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    rol TEXT DEFAULT 'miembro'::text NOT NULL CHECK (rol IN ('miembro', 'lider', 'pastor_admin')),
    celula_id BIGINT REFERENCES public.celulas ON DELETE SET NULL,
    ministerio_id BIGINT REFERENCES public.ministerios ON DELETE SET NULL,
    tel TEXT,
    direccion TEXT,
    fecha_nacimiento DATE,
    fecha_ingreso DATE,
    como_llego TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Agregar Foreign Keys circulares para los líderes/coordinadores ahora que la tabla de perfiles existe
ALTER TABLE public.celulas ADD CONSTRAINT fk_celulas_lider FOREIGN KEY (lider_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.ministerios ADD CONSTRAINT fk_ministerios_coordinador FOREIGN KEY (coordinador_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- Tabla de Historial Espiritual (ciclo de clases)
CREATE TABLE IF NOT EXISTS public.spiritual_records (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    bautizado BOOLEAN DEFAULT false NOT NULL,
    fecha_bautismo DATE,
    conectar BOOLEAN DEFAULT false NOT NULL, -- Clase Conectar
    crecer BOOLEAN DEFAULT false NOT NULL,   -- Clase Crecer
    intro_lid BOOLEAN DEFAULT false NOT NULL, -- Clase Intro Liderazgo
    dones BOOLEAN DEFAULT false NOT NULL,     -- Clase Descubre tus Dones
    aplicadas BOOLEAN DEFAULT false NOT NULL, -- Clase Herramientas Aplicadas
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Devocionales Publicados
CREATE TABLE IF NOT EXISTS public.devocionales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana INTEGER NOT NULL,
    titulo TEXT NOT NULL,
    texto_biblico TEXT NOT NULL, -- Ejemplo: "Filipenses 4:6-7"
    reflexion TEXT NOT NULL,
    oracion TEXT NOT NULL,
    pdf_url TEXT,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla del Diario Devocional Personal (Journaling)
CREATE TABLE IF NOT EXISTS public.devotional_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    devocional_id BIGINT REFERENCES public.devocionales(id) ON DELETE CASCADE NOT NULL,
    apreciacion TEXT NOT NULL,       -- Bloque 1: Lo que Dios me dijo
    cambios TEXT NOT NULL,            -- Bloque 2: Cosas a cambiar
    oracion_personal TEXT NOT NULL,   -- Bloque 3: Motivos de oración
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, devocional_id)
);

-- Tabla de Notas Pastorales Privadas (Acceso exclusivo a pastores)
CREATE TABLE IF NOT EXISTS public.pastoral_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Alertas de Seguimiento Pastoral
CREATE TABLE IF NOT EXISTS public.people_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    tipo TEXT NOT NULL, -- Ejemplo: "Inactividad", "Apoyo Espiritual", "Salud"
    descripcion TEXT NOT NULL,
    resuelta BOOLEAN DEFAULT false NOT NULL,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Pueblos No Alcanzados (Misiones)
CREATE TABLE IF NOT EXISTS public.missions_pueblos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    region TEXT NOT NULL,
    poblacion INTEGER,
    religion TEXT,
    porcentaje_cristiano NUMERIC(5,2),
    activo BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
-- =========================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.celulas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ministerios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spiritual_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devocionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devotional_journal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pastoral_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.people_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_pueblos ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 3. FUNCIONES HELPER DE ROLES (SECURITY DEFINER para evitar recursión RLS)
-- =========================================================================

-- Verifica si el usuario actual es 'pastor_admin'
CREATE OR REPLACE FUNCTION public.is_pastor_admin()
RETURNS BOOLEAN SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND rol = 'pastor_admin'
  );
END;
$$ LANGUAGE plpgsql;

-- Verifica si el usuario actual es 'lider' o superior
CREATE OR REPLACE FUNCTION public.is_lider()
RETURNS BOOLEAN SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND rol IN ('lider', 'pastor_admin')
  );
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- 4. POLÍTICAS DE ACCESO (RLS POLICIES)
-- =========================================================================

-- --- PROFILES ---
CREATE POLICY "Permitir lectura de perfil propio" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Permitir lectura de perfiles a líderes y pastores" ON public.profiles
    FOR SELECT USING (public.is_lider());

CREATE POLICY "Permitir actualización de perfil propio" ON public.profiles
    FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE POLICY "Permitir a pastores administrar perfiles y roles" ON public.profiles
    FOR ALL USING (public.is_pastor_admin());

-- --- CÉLULAS ---
CREATE POLICY "Permitir ver células a usuarios autenticados" ON public.celulas
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar células a pastores" ON public.celulas
    FOR ALL USING (public.is_pastor_admin());

-- --- MINISTERIOS ---
CREATE POLICY "Permitir ver ministerios a usuarios autenticados" ON public.ministerios
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar ministerios a pastores" ON public.ministerios
    FOR ALL USING (public.is_pastor_admin());

-- --- SPIRITUAL RECORDS ---
CREATE POLICY "Permitir ver registro espiritual propio" ON public.spiritual_records
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Permitir ver registros espirituales a líderes y pastores" ON public.spiritual_records
    FOR SELECT USING (public.is_lider());

CREATE POLICY "Permitir actualizar registros espirituales a líderes y pastores" ON public.spiritual_records
    FOR UPDATE USING (public.is_lider());

CREATE POLICY "Permitir administrar registros espirituales a pastores" ON public.spiritual_records
    FOR ALL USING (public.is_pastor_admin());

-- --- DEVOCIONALES ---
CREATE POLICY "Permitir ver devocionales a usuarios autenticados" ON public.devocionales
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar devocionales a pastores" ON public.devocionales
    FOR ALL USING (public.is_pastor_admin());

-- --- DEVOTIONAL JOURNAL (DIARIO) ---
CREATE POLICY "Permitir ver diario propio" ON public.devotional_journal
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Permitir insertar diario propio" ON public.devotional_journal
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Permitir actualizar diario propio" ON public.devotional_journal
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Permitir borrar diario propio" ON public.devotional_journal
    FOR DELETE USING (auth.uid() = user_id);

-- --- NOTES PASTORALES ---
CREATE POLICY "Acceso exclusivo a pastores para notas pastorales" ON public.pastoral_notes
    FOR ALL USING (public.is_pastor_admin());

-- --- ALERTAS ---
CREATE POLICY "Acceso exclusivo a pastores para alertas de seguimiento" ON public.people_alerts
    FOR ALL USING (public.is_pastor_admin());

-- --- MISIONES (PUEBLOS) ---
CREATE POLICY "Permitir ver pueblos a usuarios autenticados" ON public.missions_pueblos
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar pueblos a líderes y pastores" ON public.missions_pueblos
    FOR ALL USING (public.is_lider());

-- =========================================================================
-- 5. TRIGGER DE CREACIÓN AUTOMÁTICA DE PERFIL AL REGISTRARSE
-- =========================================================================

-- Función del disparador
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- Insertar perfil de usuario
  INSERT INTO public.profiles (id, email, nombre, rol)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'nombre', new.raw_user_meta_data->>'name', 'Miembro Nuevo'),
    'miembro'
  );

  -- Insertar registro espiritual vacío por defecto
  INSERT INTO public.spiritual_records (user_id)
  VALUES (new.id);

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger asociado a auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================================
-- 6. DATOS INICIALES (SEED DATA)
-- =========================================================================

-- Insertar células iniciales de prueba
INSERT INTO public.celulas (nombre, dia, hora, lugar) VALUES
('Célula Providencia', 'Miércoles', '20:00', 'Metro Los Leones'),
('Célula Las Condes', 'Jueves', '19:30', 'Av. Apoquindo'),
('Célula Ñuñoa Jóvenes', 'Martes', '19:00', 'Plaza Ñuñoa')
ON CONFLICT DO NOTHING;

-- Insertar ministerios iniciales
INSERT INTO public.ministerios (nombre, descripcion) VALUES
('Misiones', 'Evangelización transcultural y apoyo a misioneros en el campo.'),
('Escuela de Líderes', 'Formación de nuevos líderes espirituales de la congregación.'),
('Deportes y Recreación', 'Conexión comunitaria a través de actividades deportivas.')
ON CONFLICT DO NOTHING;

-- Insertar devocionales de muestra para el arranque
INSERT INTO public.devocionales (semana, titulo, texto_biblico, reflexion, oracion) VALUES
(23, 'La paz que sobrepasa todo entendimiento', 'Filipenses 4:6-7', 
 'En un mundo lleno de ansiedad y prisas constantes, el apóstol Pablo nos insta a no afanarnos por nada. La clave para la paz interior reside en llevar todas nuestras peticiones delante de Dios a través de la oración y la acción de gracias. Cuando entregamos nuestras cargas a Él, Su paz, que supera toda capacidad humana de análisis, monta guardia en nuestros corazones y mentes.', 
 'Señor Jesús, hoy decido entregar en Tus manos cada una de mis preocupaciones. Te doy gracias por Tu amor incondicional y te pido que Tu paz inunde mi mente y guarde mi corazón frente a cualquier tempestad. Amén.'),
(23, 'Permanecer en la Vid', 'Juan 15:4-5', 
 'Jesús utiliza la analogía de la vid y los pámpanos para ilustrar nuestra total dependencia de Él. Un pámpano no puede dar fruto por sí mismo si no permanece unido a la vid; del mismo modo, nuestras vidas carecerán de verdadero fruto espiritual si nos desconectamos de Su presencia diaria. Permanecer implica intimidad, comunión constante y obediencia.', 
 'Padre Celestial, reconozco que separado de ti nada puedo hacer. Ayúdame a buscarte en intimidad cada mañana, a nutrirme de Tu Palabra y a permanecer conectado a Ti durante todo mi día. Amén.')
ON CONFLICT DO NOTHING;
