-- =========================================================================
-- VIDA NUEVA APP - MIGRACIÓN SQL MVP 4
-- Iglesia Bautista Vida Nueva, Santiago, Chile
-- =========================================================================

-- 1. CREACIÓN DE NUEVAS TABLAS

-- Tabla de Actividades Deportivas
CREATE TABLE IF NOT EXISTS public.sports_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    sport_type TEXT NOT NULL, -- e.g., 'Fútbol / Baby Fútbol', 'Senderismo / Trekking', 'Básquetbol', 'Recreación Familiar'
    datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    place TEXT NOT NULL,
    limit_slots INTEGER NOT NULL DEFAULT 10,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Inscripción de Participantes
CREATE TABLE IF NOT EXISTS public.sports_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.sports_activities(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(activity_id, user_id)
);

-- Tabla de Recursos (Biblioteca Digital)
CREATE TABLE IF NOT EXISTS public.recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL, -- e.g., 'Manuales', 'Escuela', 'Kit Replicable'
    file_url TEXT NOT NULL,
    downloads_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
-- =========================================================================
ALTER TABLE public.sports_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sports_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recursos ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 3. POLÍTICAS DE ACCESO (RLS POLICIES)
-- =========================================================================

-- --- ACTIVIDADES DEPORTIVAS ---
CREATE POLICY "Permitir ver actividades a usuarios autenticados" ON public.sports_activities
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar actividades a líderes y pastores" ON public.sports_activities
    FOR ALL USING (public.is_lider());

-- --- INSCRIPCIONES DEPORTIVAS ---
CREATE POLICY "Permitir ver inscripciones a usuarios autenticados" ON public.sports_registrations
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir registrar inscripción propia" ON public.sports_registrations
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Permitir cancelar inscripción propia o lider" ON public.sports_registrations
    FOR DELETE USING (auth.uid() = user_id OR public.is_lider());

-- --- RECURSOS ---
CREATE POLICY "Permitir ver recursos a usuarios autenticados" ON public.recursos
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar recursos a líderes y pastores" ON public.recursos
    FOR ALL USING (public.is_lider());


-- =========================================================================
-- 4. TRIGGER Y FUNCIÓN PARA CONTROL DE CUPOS (CONCURRENCIA)
-- =========================================================================
CREATE OR REPLACE FUNCTION public.check_sports_registration_slots()
RETURNS TRIGGER AS $$
DECLARE
    slots_limit INTEGER;
    slots_taken INTEGER;
BEGIN
    -- Bloquear y leer la actividad correspondiente para prevenir condiciones de carrera concurrentes
    SELECT limit_slots INTO slots_limit
    FROM public.sports_activities
    WHERE id = NEW.activity_id
    FOR UPDATE;

    -- Contar inscripciones existentes
    SELECT COUNT(*) INTO slots_taken
    FROM public.sports_registrations
    WHERE activity_id = NEW.activity_id;

    -- Verificar si se excede el límite
    IF slots_taken >= slots_limit THEN
        RAISE EXCEPTION 'No quedan cupos disponibles para esta actividad deportiva.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_check_sports_slots
BEFORE INSERT ON public.sports_registrations
FOR EACH ROW
EXECUTE FUNCTION public.check_sports_registration_slots();


-- =========================================================================
-- 5. DATOS DE PRUEBA (SEED DATA)
-- =========================================================================

-- Eventos Deportivos Semilla
INSERT INTO public.sports_activities (title, description, sport_type, datetime, place, limit_slots) VALUES
('Campeonato Relámpago de Baby Fútbol', 'Gran encuentro deportivo masculino y femenino de la congregación. ¡Arma tu equipo o ven y te sumamos a uno!', 'Fútbol / Baby Fútbol', now() + interval '3 days', 'Gimnasio Municipal de Macul', 14),
('Trekking Familiar Cerros de Chena', 'Senderismo de dificultad media-baja. Apto para niños sobre 8 años. Llevar hidratación y calzado cómodo.', 'Senderismo / Trekking', now() + interval '5 days', 'Parque Cerro Chena, San Bernardo', 30),
('Torneo 3x3 Básquetbol Vida Nueva', 'Torneo amistoso en equipos de tres. Premios sorpresa para el primer lugar.', 'Básquetbol', now() + interval '10 days', 'Cancha del Parque Inés de Suárez', 12)
ON CONFLICT DO NOTHING;

-- Recursos Semilla
INSERT INTO public.recursos (title, description, category, file_url) VALUES
('Manual del Discipulador Cristiano', 'Guía completa con 12 lecciones esenciales para mentores que guían a nuevos creyentes en su caminar de fe.', 'Manuales', 'https://aplaleroakbaaltejeif.supabase.co/storage/v1/object/public/recursos/manual_discipulador.pdf'),
('Guía del Líder - Escuela de Líderes', 'Material de apoyo docente con dinámicas de grupo, explicaciones teológicas adicionales y pautas de evaluación.', 'Escuela', 'https://aplaleroakbaaltejeif.supabase.co/storage/v1/object/public/recursos/guia_escuela_lideres.pdf'),
('Kit Replicable: Vida Nueva App Setup Guide', 'Manual técnico y administrativo detallado para implementar y configurar el sistema de Vida Nueva App (React, Supabase y Vercel) en cualquier congregación Bautista.', 'Kit Replicable', 'https://aplaleroakbaaltejeif.supabase.co/storage/v1/object/public/recursos/kit_replicacion_vna.pdf')
ON CONFLICT DO NOTHING;
