-- =========================================================================
-- VIDA NUEVA APP - MIGRACIÓN SQL MVP 2
-- Iglesia Bautista Vida Nueva, Santiago, Chile
-- =========================================================================

-- 1. ALTAS Y ALTERACIONES DE TABLAS EXISTENTES
-- Agregar columna mentor_id a la tabla de perfiles (FK circular a profiles)
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS mentor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

-- 2. CREACIÓN DE NUEVAS TABLAS MINISTERIALES

-- Tabla de Misioneros Apoyados
CREATE TABLE IF NOT EXISTS public.missions_misioneros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    pais_servicio TEXT NOT NULL,
    historia TEXT NOT NULL,
    pedido_oracion TEXT NOT NULL,
    foto_url TEXT,
    contacto_email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Actualizaciones y Cartas de Misioneros
CREATE TABLE IF NOT EXISTS public.missions_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    misionero_id BIGINT REFERENCES public.missions_misioneros(id) ON DELETE CASCADE NOT NULL,
    titulo TEXT NOT NULL,
    contenido TEXT NOT NULL,
    fecha DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Testimonios Misioneros (Motivar)
CREATE TABLE IF NOT EXISTS public.missions_testimonios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    autor TEXT NOT NULL,
    contenido TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Viajes Misioneros Programados (Movilizar)
CREATE TABLE IF NOT EXISTS public.missions_viajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino TEXT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    descripcion TEXT NOT NULL,
    requisitos TEXT NOT NULL,
    lider_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Cursos de Preparación Misionera (Entrenar)
CREATE TABLE IF NOT EXISTS public.missions_cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    url_material TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Compromisos de Oración por Pueblos No Alcanzados
CREATE TABLE IF NOT EXISTS public.missions_oracion_registro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    pueblo_id BIGINT REFERENCES public.missions_pueblos(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, pueblo_id)
);

-- =========================================================================
-- 3. HABILITAR ROW LEVEL SECURITY (RLS)
-- =========================================================================
ALTER TABLE public.missions_misioneros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_testimonios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_viajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions_oracion_registro ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 4. POLÍTICAS DE ACCESO (RLS POLICIES)
-- =========================================================================

-- --- MISIONEROS ---
CREATE POLICY "Permitir ver misioneros a usuarios autenticados" ON public.missions_misioneros
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar misioneros a pastores" ON public.missions_misioneros
    FOR ALL USING (public.is_pastor_admin());

-- --- ACTUALIZACIONES ---
CREATE POLICY "Permitir ver actualizaciones a usuarios autenticados" ON public.missions_updates
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar actualizaciones a pastores y líderes" ON public.missions_updates
    FOR ALL USING (public.is_lider());

-- --- TESTIMONIOS ---
CREATE POLICY "Permitir ver testimonios a usuarios autenticados" ON public.missions_testimonios
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar testimonios a pastores y líderes" ON public.missions_testimonios
    FOR ALL USING (public.is_lider());

-- --- VIAJES MISIONEROS ---
CREATE POLICY "Permitir ver viajes a usuarios autenticados" ON public.missions_viajes
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar viajes a pastores y líderes" ON public.missions_viajes
    FOR ALL USING (public.is_lider());

-- --- CURSOS ---
CREATE POLICY "Permitir ver cursos a usuarios autenticados" ON public.missions_cursos
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir administrar cursos a pastores y líderes" ON public.missions_cursos
    FOR ALL USING (public.is_lider());

-- --- COMPROMISOS DE ORACIÓN ---
CREATE POLICY "Permitir ver compromisos de oración propios" ON public.missions_oracion_registro
    FOR SELECT USING (auth.uid() = user_id OR public.is_pastor_admin());

CREATE POLICY "Permitir registrar compromiso propio" ON public.missions_oracion_registro
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Permitir borrar compromiso propio" ON public.missions_oracion_registro
    FOR DELETE USING (auth.uid() = user_id);

-- =========================================================================
-- 5. DATOS DE PRUEBA (SEED DATA)
-- =========================================================================

-- Asegurar que existe el Pueblo del Mes
INSERT INTO public.missions_pueblos (nombre, region, poblacion, religion, porcentaje_cristiano, activo) VALUES
('Pueblo Wolof', 'Senegal, África Occidental', 5200000, 'Islam (Sufismo)', 0.10, true),
('Pueblo Baluchis', 'Baluchistán (Pakistán/Irán)', 9500000, 'Islam (Sunita)', 0.02, false)
ON CONFLICT DO NOTHING;

-- Insertar Misioneros de prueba
INSERT INTO public.missions_misioneros (nombre, pais_servicio, historia, pedido_oracion, contacto_email) VALUES
('Familia Silva (Andrés y María)', 'India', 'Andrés y María sirven en comunidades rurales del norte de la India, coordinando una pequeña escuela infantil de nivel básico y prestando asistencia médica comunitaria gratuita en terreno.', 'Por la provisión mensual de la escuela de niños, salud familiar y sabiduría para la relación diaria con los líderes comunales locales.', 'silva.india@vidanueva.cl'),
('Esteban y Laura', 'Marruecos', 'Esteban y Laura se encuentran en el norte de África desarrollando proyectos de traducción, clases de idiomas gratuitas para jóvenes universitarios locales y talleres de capacitación tecnológica.', 'Por protección personal, guía para profundizar relaciones con estudiantes locales y buen progreso en el idioma árabe.', 'esteban.laura@vidanueva.cl')
ON CONFLICT DO NOTHING;

-- Insertar Actualizaciones de misioneros
INSERT INTO public.missions_updates (misionero_id, titulo, contenido, fecha) VALUES
(1, 'Inauguración del ciclo escolar 2026', 'Estamos muy contentos de reportar que este lunes iniciamos clases con 35 niños registrados. La provisión de uniformes y útiles escolares llegó justo a tiempo gracias a la ofrenda anual de Vida Nueva. ¡Los niños están muy entusiasmados por aprender!', '2026-06-01'),
(2, 'Taller de programación en el centro juvenil', 'Esta semana finalizamos el primer taller de HTML y CSS para estudiantes locales. Asistieron 12 jóvenes que se mostraron muy agradecidos. Esto nos ha permitido iniciar conversaciones profundas sobre nuestra fe en el día a día. Sigamos orando por ellos.', '2026-05-25')
ON CONFLICT DO NOTHING;

-- Insertar Testimonios misioneros
INSERT INTO public.missions_testimonios (titulo, autor, contenido) VALUES
('Ver el obrar de Dios en Calbuco', 'Camila Jara', 'Formar parte del equipo juvenil que viajó al sur de Chile fue una experiencia transformadora. Al principio sentía temor de no poder comunicar bien la Palabra, pero al conversar cara a cara con las familias y ver su necesidad de contención espiritual, entendí que Dios nos usa en nuestra debilidad. ¡Las misiones locales valen la pena!'),
('Mi oración cambia las cosas', 'Jorge Valenzuela', 'Pensaba que si no viajaba no estaba haciendo misiones, pero tras comprometerme a orar diariamente por el Pueblo Wolof este año, mi perspectiva cambió. Dios ha ensanchado mi corazón y me ha enseñado a clamar con pasión por personas que nunca he visto en persona.')
ON CONFLICT DO NOTHING;

-- Cursos de capacitación
INSERT INTO public.missions_cursos (titulo, descripcion, url_material) VALUES
('Introducción a las Misiones Transculturales', 'Curso de 4 sesiones sobre fundamentos bíblicos e históricos de las misiones mundiales y adaptación cultural.', 'https://vidanueva.app/material/misiones_101.pdf'),
('Cosmovisión Islámica y Relaciones Prácticas', 'Material práctico para comprender el pensamiento musulmán y establecer relaciones de confianza y respeto mutuo.', 'https://vidanueva.app/material/cosmovision_islam.pdf')
ON CONFLICT DO NOTHING;

-- Viajes Misioneros programados
INSERT INTO public.missions_viajes (destino, fecha_inicio, fecha_fin, descripcion, requisitos) VALUES
('Misión Temuco (Región de la Araucanía)', '2026-07-15', '2026-07-22', 'Apoyo social y construcción para una congregación rural aliada. Incluye talleres de discipulado infantil y escuela bíblica de vacaciones.', 'Ser miembro formal de la iglesia, participar en el entrenamiento de preparación los sábados y contar con aprobación del equipo pastoral.')
ON CONFLICT DO NOTHING;
